Import EverNifeHyCore to this project, unifying it:
Commits:

Lets use maven.hytale.com rather than local binary jar Pétrus Pradella 25/02/2026 21:12
OptImports and add ECPlayerDataEvent Pétrus Pradella 08/02/2026 16:43
Small fixes for FCReflectionUtil Pétrus Pradella 08/02/2026 02:36
Create an ECListener event handler registerer to make my life easier Pétrus Pradella 08/02/2026 02:30
Fire ECPluginReloadEvents on Pre and Post states Pétrus Pradella 08/02/2026 02:29
Create ECEventHandler annotation and priority Pétrus Pradella 08/02/2026 02:23
Add some dependency order Pétrus Pradella 07/02/2026 05:16
Create InnerPAPIRegisterer to prevent java.lang.NoClassDefFoundError Pétrus Pradella 07/02/2026 05:16
Missed fields Pétrus Pradella 07/02/2026 04:55
Implement PAPIIntegration Pétrus Pradella 07/02/2026 04:55
Implement PAPIIntegration Pétrus Pradella 07/02/2026 04:55
Add Vault and PAPI dependencies Pétrus Pradella 07/02/2026 04:54
Add future way to unregisterAll on the ECListeners Pétrus Pradella 07/02/2026 01:29
Add basics of ActionBarAPI Pétrus Pradella 07/02/2026 01:29
Implemente ComparableItem and ComparableItemComplex with FCItemUtils Pétrus Pradella 06/02/2026 21:33
Implement VaultIntegration with VaultUnlocked Pétrus Pradella 06/02/2026 20:44
Add SVDataManager Pétrus Pradella 02/02/2026 18:53
missed copy world name on safeTargetLocation Pétrus Pradella 31/01/2026 03:54
Fix giveItemsTo send message when it should not Pétrus Pradella 29/01/2026 02:28
Fix FancyText broadcast Pétrus Pradella 29/01/2026 02:27
Bring back CMDAlias Pétrus Pradella 29/01/2026 02:27
Add FCHytaleUtil::broadcastMessage Pétrus Pradella 29/01/2026 01:22
Create a way to giveItemsTo and drop the remaining items on the ground Pétrus Pradella 29/01/2026 01:21
Once more, i hope the last time, adjust the teleportation flow '-' Pétrus Pradella 29/01/2026 01:21
Add parseItem on input reader Pétrus Pradella 29/01/2026 01:21
The getLocation should return a clone of the position '-' Pétrus Pradella 28/01/2026 22:19
Register CMDItemInfo Pétrus Pradella 28/01/2026 22:04
Add LuckPermsIntegration Pétrus Pradella 28/01/2026 21:48
Should replace here '-' Pétrus Pradella 28/01/2026 21:04
More temporary unicode conversions... when hytale will have a decent chat? Pétrus Pradella 28/01/2026 21:01
Simplify messages Pétrus Pradella 28/01/2026 20:56
Create CfgLoadableSalvable for the Pos system Pétrus Pradella 28/01/2026 20:16
Improve serialization speed Pétrus Pradella 28/01/2026 20:16
Finally fix the teleportation even from different worlds Pétrus Pradella 28/01/2026 20:08
Properly save the Vectors of hytale Pétrus Pradella 28/01/2026 20:08
Create BlockPos, ChukPos, RegionPos and LocPos to simplify math operations Pétrus Pradella 28/01/2026 14:12
Fix teleport logic Pétrus Pradella 25/01/2026 17:14
Add firstSeen tracker on PlayerData Pétrus Pradella 25/01/2026 03:48
Small fixes on durability Pétrus Pradella 25/01/2026 03:46
Small fixes Pétrus Pradella 24/01/2026 20:09
Enforce FCPlayerInventory to keep track of all inventories Pétrus Pradella 24/01/2026 19:56
Always shadow all dependencies Pétrus Pradella 24/01/2026 19:55
Fix Argumento not properly comparing plugin name with group Pétrus Pradella 24/01/2026 19:54
Add way to get player's target block! Pétrus Pradella 24/01/2026 18:54
Add save for Vector3i Pétrus Pradella 24/01/2026 18:53
Small adjustments on FCPlayerInventory Pétrus Pradella 24/01/2026 07:22
Add way to save ItemStack on yaml using ItemDataPart Pétrus Pradella 24/01/2026 07:22
Create FCPlayerInventory Pétrus Pradella 24/01/2026 07:10
Add /iteminfo command Pétrus Pradella 24/01/2026 06:52
Fix ItemStack held item extractor of CMDMethodInterpreter Pétrus Pradella 24/01/2026 06:45
Implement ItemDataPart system on Hytale using ItemId, Metadata, Durability, MaxDurability and Quantity... hope its enough Pétrus Pradella 24/01/2026 06:26
Create the basics of FCItemFactory that will just clone an ItemStack Pétrus Pradella 24/01/2026 06:02
Add way to get the World and the Player of a HytaleFPlayer Pétrus Pradella 24/01/2026 06:02
Small change on location Pétrus Pradella 23/01/2026 00:11
These dependencies are optional Pétrus Pradella 22/01/2026 02:02
Even more adaptions on the teleport flow Pétrus Pradella 22/01/2026 02:02
Even more adaptions on the teleport flow, lets ensure the chunk is loaded '-' Pétrus Pradella 17/01/2026 01:00
ILoveTheScheduler - More changes Pétrus Pradella 17/01/2026 00:59
Add some locks Pétrus Pradella 16/01/2026 23:50
More changes at HytaleFPlayer Pétrus Pradella 16/01/2026 19:49
Wrap PlayeRef on Argumento.getPlayer() to be done async Pétrus Pradella 16/01/2026 19:49
Rework Location save way Pétrus Pradella 16/01/2026 19:48
When on same thread, SynchronizedAction::runAndGet should not cause error Pétrus Pradella 16/01/2026 19:48
Add more descriptive error when getting wrong delegate Pétrus Pradella 16/01/2026 19:43
Change data-folders to respect Hytale pattern Pétrus Pradella 16/01/2026 14:01
More parameter type adapter.... i really need ot remake this system '-' Pétrus Pradella 16/01/2026 14:01
Add way to get Player's World and to teleport a player Pétrus Pradella 16/01/2026 02:24
More arg fixes Pétrus Pradella 16/01/2026 02:24
Some command adjustments Pétrus Pradella 16/01/2026 02:03
Add more possible command args Pétrus Pradella 16/01/2026 00:47
Add FCScheduler Actions to be Executed on the World Thread Pétrus Pradella 16/01/2026 00:21
OptImports Pétrus Pradella 16/01/2026 00:17
Create SynchronizedActions Pétrus Pradella 16/01/2026 00:17
Adapt more FPlayers Pétrus Pradella 15/01/2026 23:16
Use FPlayer to make my life easier! Pétrus Pradella 15/01/2026 22:31
Create common FPlayer to make my life easier! Pétrus Pradella 15/01/2026 21:27
Create common FCommandSender to make my life easier! Pétrus Pradella 15/01/2026 20:35
Use IMessageReceiver on Fancytext Pétrus Pradella 15/01/2026 15:50
Dump Version Pétrus Pradella 15/01/2026 00:57
Add icon Pétrus Pradella 15/01/2026 00:51
Add README.md Pétrus Pradella 15/01/2026 00:50
[Here comes, the Mighty Duster!!] Port EverNifeCore to Hytale! Pétrus Pradella 15/01/2026 00:34
Add basics of EverNifeHyCore Pétrus Pradella 15/01/2026 00:30